import { env } from "./env";

export type RegisterBrowser = {
	/**
	 * The UUID of the app to register the browser with
	 */
	appUuid: string;
	/**
	 * The browser's unique identifier
	 */
	browserUuid: string;
	/**
	 * The endpoint generated by the browser to send the subscription to
	 */
	endpoint: string;
	/**
	 * The keys generated by the browser to encrypt and authenticate
	 * the notifications
	 */
	keys: {
		/**
		 * The public key to encrypt the notifications
		 */
		publicKey: string;
		/**
		 * The authentication secret for the notifications
		 */
		authenticationSecret: string;
	};
	/**
	 * Your unique identifier for this user
	 */
	userId?: string;
	/**
	 * The timezone of this browser
	 */
	timezone?: string;
};

export function registerBrowser({
	appUuid,
	browserUuid,
	userId,
	endpoint,
	keys,
	timezone,
}: RegisterBrowser) {
	return fetch(`${env.API_ENDPOINT}/${env.API_VERSION}/browser`, {
		method: "POST",
		headers: {
			"x-app-uuid": appUuid,
		},
		body: JSON.stringify({
			browserUuid,
			userId,
			endpoint,
			keys,
			timezone,
		}),
	});
}
